### ISSUE TITLE
File location?

### ISSUE THREAD

**Issue by rayyy12** [manuGMG/1fichier-dl#20]
It says completed on the status and 100% on progress. Do I need to save the file or is it not downloaded yet? I can't find my downloaded files.

**Comment by lightblair** [comment]
The download location is in the settings

**Comment by skideric** [comment]
Yeah,this APP IS USELESS! Downloads to C:/System Drive.... NOT LOCATION YOU SET IT TOO!
Now i have to figure out WHERE THE HELL IT DOWNLOADED to,because it EMPTIED my c: DRIVE!

**Comment by manuGMG** [comment]
As stated, default download location is 1fichier-dl root directory.

You should change it before downloading from **Settings**.
