### ISSUE TITLE
How do I type the password for protected files?

### ISSUE THREAD

**Issue by ElTioRata** [manuGMG/1fichier-dl#23]
I don't see any pop-up window or anything to input a password for downloading protected files.

**Comment by lightblair** [comment]
The last box is where the password goes 
![image](https://user-images.githubusercontent.com/20854744/128185385-894fea2d-5fdd-43c5-b6b3-71d74a383728.png)

**Comment by ElTioRata** [comment]
Just figured it today, thanks anyways!
