### ISSUE TITLE
EXE crashes or get stuck downloading big files

### ISSUE THREAD

**Issue by Darkseid186** [manuGMG/1fichier-dl#26]
The app works perfectly with smaller files (so far under 1gb) but whenever I try to download larger files (so far tested with 7gb files and above), the progress of the app hangs at around 100% and doesn't seem to download any further (download speed doesn't change, disk space doesn't change). On a few files, the .unfinished file are close to the actual sizes of the download but after leaving it on for another half an hour nothing really changes. Lastly, when I try to pause and resume the download the app just exits itself leaving me with the .unfinished file. Hope the issue has a clear and simple solution and the app had been very useful, many thanks.

**Comment by manuGMG** [comment]
Will try to reproduce this.
