### ISSUE TITLE
Number near "Bypassing" status

### ISSUE THREAD

**Issue by Denny-89** [manuGMG/1fichier-dl#27]
Sorry for opening an issue but i couldn't find anywhere what those numbers mean. I thought that's the order of downloads until they started to randomly change.

Also could we please get a new exe build with all commits since v0.1.4 or instructions of how to compile it ourselves (googling doesn't show anything useful)? Thank you.

**Comment by oureveryday** [comment]
It means retries times.

**Comment by manuGMG** [comment]
Assuming you have Python3 installed and correctly added to PATH, just do `pip install -r requirements.txt` and run `python3 gui.py`.
