### ISSUE TITLE
Clicking resume on a paused download wont resume it (does nothing).

### ISSUE THREAD

**Issue by harrywon2020** [manuGMG/1fichier-dl#3]
Clicking resume on a paused download wont resume it (does nothing).

**Comment by manuGMG** [comment]
Does this always happens to you, or just in some specific situations?

**Comment by harrywon2020** [comment]
Just happened the once in that situation. If I encounter this again, ill post here.

**Comment by harrywon2020** [comment]
> Does this always happens to you, or just in some specific situations?

Just happened the once in that situation. If I encounter this again, ill post here. Cheers
