### ISSUE TITLE
stuck on pypass

### ISSUE THREAD

**Issue by RedCommand** [manuGMG/1fichier-dl#32]
Seem like the proxy is broken

python cli.py https://1fichier.com/\?#########
Starting download: https://1fichier.com/?########..
Bypassing..
Bypassing..
Bypassing..
Bypassing..
Bypassing..
Bypassing..
Bypassing..
Bypassing..
Bypassing..

**Comment by manuGMG** [comment]
CLI version was removed from main branch.
Test with new GUI release (v0.1.5), bypassing should be smoother now.

**Comment by RedCommand** [comment]
I think there is a problem with the proxy because I have the same problem with the GUI (it is the latest release and i have tried different network...)
am I doing something wrong, or every one has the same problem ?
btw I am in France (I don't know how proxy works, but it may be related)

**Comment by manuGMG** [comment]
Could you share `logs` after running the app for some minutes? 
You should find log file in root folder (`1fichier-dl/logs`).

**Comment by RedCommand** [comment]
[logs.txt](https://github.com/manuGMG/1fichier-dl/files/7111475/logs.txt)

here is my logs file (I rename it logs.txt because GitHub doesn't support file without extension)
the program run for about 20 minutes

**Comment by RedCommand** [comment]
ok, i forgot to add the proxy option in my settings, i tryed with the same setting as you (https://i.imgur.com/1j52TMB.png) but now, it seams like it can't get a connection with the proxy :
![image](https://user-images.githubusercontent.com/50780743/132125191-33ce626c-8551-4750-bd57-bf4c29bd549b.png)
 here is my current logs :
![image](https://user-images.githubusercontent.com/50780743/132125229-7be9cc2f-dbc3-44aa-93e6-b24bc426ba98.png)

and the txt file is my previous log (when i run the program whout any setting in proxy settings)
[logs.txt](https://github.com/manuGMG/1fichier-dl/files/7111483/logs.txt)

**Comment by Azzhoe** [comment]
I'm also getting Bypassing status as well with the latest version.
