### ISSUE TITLE
Crashes after adding a link

### ISSUE THREAD

**Issue by ZombeeRitual** [manuGMG/1fichier-dl#36]
The download target shows up briefly before the application crashes. 

DEBUG:root:No cached downloads.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 1fichier.com:443
DEBUG:urllib3.connectionpool:https://1fichier.com:443 "GET /?xxxxxxxxxxxxxxx HTTP/1.1" 200 None
DEBUG:root:Getting proxy.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 1fichier.com:443
DEBUG:urllib3.connectionpool:https://1fichier.com:443 "POST /?xxxxxxxxxxxxxx HTTP/1.1" 200 None
DEBUG:root:Proxy worked.
DEBUG:root:Failed to parse direct link.
DEBUG:root:Getting proxy.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.proxyscan.io:443

Apologies if the fix is simple, I simply am not experienced enough to troubleshoot it on my own and am not aware of any necessary setup required prior to using this application.

**Comment by paulo27ms** [comment]
Seems like an issue with the 1fichier link itself (maybe you're trying a folder? not sure if it's supported).
