### ISSUE TITLE
Does this run on linux or is only windows10 supported? It’s Python after all..?

### ISSUE THREAD

**Issue by github-userx** [manuGMG/1fichier-dl#41]

**Comment by mjrawesome** [comment]
> It should run on Linux, tested it on Ubuntu.

Can it run headless (via CLI on a server) or does it require a UI?

**Comment by Cruzan80** [comment]
Can you help with how exactly you run this on Linux? Trying to get it on Ubuntu, but no luck so far. Have Python 3 and PyQt5 installed, not sure what next (equivalent of the .exe file for the windows version). Thanks!

**Comment by github-userx** [comment]
Personally, I installed the necessary packages in a virtual Environment (virtualenv or pip3 -m venv) and then just started the app with python3 gui.py

It worked but links and download history weren’t saved.
