### ISSUE TITLE
stuck on Bypassing

### ISSUE THREAD

**Issue by RENNYHF** [manuGMG/1fichier-dl#42]

**Comment by Azzhoe** [comment]
same here

**Comment by mrw0lfe** [comment]
Same here. Maybe they've fixed the bypass method used here. Mine just goes up and beyond
![imagem](https://user-images.githubusercontent.com/12748952/139870818-f543a958-0d37-4a30-ba84-929603e364bd.png)

**Comment by nift4** [comment]
They did fix the bypass method
