### ISSUE TITLE
Empty proxy list (forked project with option to workaround the issue)

### ISSUE THREAD

**Issue by paulo27ms** [manuGMG/1fichier-dl#48]
https://www.proxyscan.io/api/proxy?type=https&format=txt&limit=20 is returning empty (issue on proxyscan.io's side)
https://www.proxyscan.io/api/proxy?format=txt&limit=20 works (but it's not HTTPS only)

Created a fork: https://github.com/paulo27ms/1fichier-dl-customproxies
That allows to use custom proxy lists as a setting.

**Comment by CesarJair** [comment]
Can you please explain me why sometimes it works with the first proxy and sometimes it tries with thousands and doesn't work? ):

**Comment by paulo27ms** [comment]
Since this is no longer maintained I'm planning to release a fork that fixes a couple of bugs and fixes what you mention as well, I'll reply back when that's done.

**Comment by paulo27ms** [comment]
I have forked the project as promised: https://github.com/paulo27ms/1fichier-dl-fork27
I have unable to build an executable for it though, unsure why, but hopefully I can figure it out eventually

**Comment by cesarasdf** [comment]
Wow, thank you very much, I am going to try it. I don't like executables that much cus I don't know where the source code is or how to edit it. I am going to give it a try and see how it goes. Right know I am using Opera's VPN and is working real good but if this works, it will be pretty handy. Thanks, again!
