### ISSUE TITLE
Check forks for updates - see inside

### ISSUE THREAD

**Issue by Buzbee** [manuGMG/1fichier-dl#49]
https://github.com/Leinad4Mind/1fichier-dl/releases/tag/v0.1.6

**Comment by sendblink23** [comment]
This version doesn't work for me, it is just stuck bypassing forever - I have not changed any settings only the dark theme, just tried running it as admin and running it normally but still the same.

![1ficherdl-issue](https://user-images.githubusercontent.com/89880399/147158175-abd570f8-723a-4926-90c1-aa40935f2efd.png)

**Comment by DJboutit** [comment]
Version 1.6 will not even open for me all the older versions load just fine but bypass does not work on all old versions
