### ISSUE TITLE
High speed transfer speeds cause the program to not respond.

### ISSUE THREAD

**Issue by NoodleKey** [manuGMG/1fichier-dl#5]
With a download speed of 30MB/s the program will be in a mostly constant state of not responding, and be unusable until a file transfer is completed. Any attempt to pause a download or otherwise interact with the program will do nothing until the file finishes transferring. 

No outright crashing, and the downloads will finish without problem. Just while a download is active it becomes almost entirely responsive. 

Possibly related:

The download speed display in the program also caps out at 16MB/s. Windows shows full speed is being used, but the program can't seem to show above 16. This could just be because the only downloads I've tried so far have been 4GB files, and the program just didn't display it fast enough. I don't currently have a large single file link on hand.

Testing with Netlimiter capping download at reasonably quick speeds, with a 4GB file: 

1. 14 MB/s - Usable, slightly laggy but fine. Can select and pause the download just fine, and it doesn't otherwise stop responding.
2. 15 MB/s - Less responsive, selecting and pausing download was highly delayed. Usable but only just.
3. 16 MB/s - Unresponsive. Delay on select and pause took so long the file actually finished transferring while it was frozen.
4. 18 MB/s - Unresponsive. Starts locking up right away. Unable to select a download or pause it. Had to close the program to test other speed. Download disappeared on restart.
5. 10 MB/s - Perfectly fine at first. Could interact with it with no problem. However, on resuming after pause I was unable to pause it again. Removing the active download actually caused a crash. This is the first outright crash I've seen and may just be a random thing.

**Comment by harrywon2020** [comment]
Experienced this exact issue. I also noticed all things you mentioned too.

**Comment by manuGMG** [comment]
Thanks for reporting this issue in such a detailed way. Will look into it asap.

**Comment by manuGMG** [comment]
Bug is now fixed in main branch. Bugfix will be also included in next release.
