### ISSUE TITLE
App crashing after adding link

### ISSUE THREAD

**Issue by OhWowOffice** [manuGMG/1fichier-dl#52]
Hello, I know that you don't maintain this project anymore but I thought that I would still leave this here.

Whenever I input a link, then click "add link", the program crashes. I've tested running it as Admin, Redownloading it, and that doesn't work. I think the problem is with the bypassing, because when I put a link in when I have no download time limit, it doesn't crash, but when I put a link while I do have a time limit, then it crashes.

**Comment by moh2310** [comment]
me too

**Comment by CalimeroOeuf** [comment]
Same for me
