### ISSUE TITLE
Download Speed Same As Guest And Registered User??

### ISSUE THREAD

**Issue by DJboutit** [manuGMG/1fichier-dl#9]
I am only getting 1.7mbps download speed is this max speed the program will do this is the same speed as guests and registered users get.  I was hoping to get 5 to 8 mbps download speed.  When downloading 3gb+ files 1.7mbps is kinda slow 8mbps would be a lot better

**Comment by manuGMG** [comment]
You should be getting max speed.

Did you compare downloading from app vs downloading from your web browser?

**Comment by DJboutit** [comment]
Download speed is the same in the app and browser

**Comment by manuGMG** [comment]
> Download speed is the same in the app and browser

This means you're getting the higher speed you can get. In fact, when downloading using 1Fichier you're not downloading as a "premium" user but you're using the speed trial 1Fichier gives to new guests.

I'll close the issue now.

**Comment by DJboutit** [comment]
When every I download fro the  1Fichier website as a guest registered user I get 1.7mbps
